# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-02 02:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField(verbose_name='Request Time')),
                ('reserv_time', models.DateTimeField(verbose_name='Reservation Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('reserved_field', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField(verbose_name='Request Time')),
                ('reserv_time', models.DateTimeField(verbose_name='Reservation Time')),
                ('end_time', models.DateTimeField(verbose_name='End Time')),
                ('reserved_field', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Room'),
        ),
        migrations.AddField(
            model_name='history',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='message.Room'),
        ),
    ]
